config/routes.rb
Rails.application.routes.draw do

   resources :users
   resources :sessions,  only: [:new, :create, :destroy]
   resources :foodposts, only: [:create, :destroy]
   root 'static_pages#home'
   match '/signup',  to: 'users#new',            via: 'get'
   match '/signin',  to: 'sessions#new',         via: 'get'
   match '/signout', to: 'sessions#destroy',     via: 'delete'
   match '/contact', to: "static_pages#contact", via: "get"
   match '/about',   to: "static_pages#about",   via: "get"
   match '/campus',  to: "static_pages#campus",  via: "get"

end

app/models/foodpost.rb
class Foodpost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('date DESC, start_time DESC') }
  default_scope -> { where('date >= ?', Time.now.beginning_of_day) }
  validates :content,    presence: true, length: { maximum: 500 }
  validates :user_id,    presence: true
  validates :date,       presence: true
  validates :start_time, presence: true
  validates :location,   presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :foodposts
  before_save { email.downcase! }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    Foodpost.all
  end

  private
    
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/foodposts_controller.rb
class FoodpostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  def index
    @foodposts = Foodpost.paginate(page: params[:page])
    if signed_in?
      @foodpost = current_user.foodposts.build
      if @foodpost.save
        redirect_to root_url
      else
        render 'foodposts/index'
      end
    end
  end

  def create
    @foodpost = current_user.foodposts.build(foodpost_params)
    if @foodpost.save
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    Foodpost.find(params[:id]).destroy
    redirect_to root_url
  end

  private
    def foodpost_params
      params.require(:foodpost).permit(:content, :date, :location,
                                       :start_time)
    end

    def correct_user
      @foodpost = current_user.foodpost.find_by(id: params[:id])
      redirect_to root_url if @foodpost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @foodpost   = current_user.foodposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @feed_items = Foodpost.paginate(page: params[:page])
    end
  end

  def contact
  end

  def about
  end

  def campus
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @foodposts = @user.foodposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to YumYum!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:succcess] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    #Before filters

    def signed_in_user
      unless signed_in?
        store location
        redirect_to signed_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/foodposts/_foodpost.html.erb
<li class="foodpost">
  <span class="date"><%= foodpost.date.strftime("%a %m/%e") %>
  @
  <span class="time"><%= foodpost.start_time.localtime.strftime("%l:%M %p") %></span>
  <span class="location"><%= foodpost.location %></span>
  <span class="content"><%= foodpost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(foodpost.created_at) %> ago.
  </span>
  <% if current_user?(foodpost.user) %>
    <%= link_to "delete", foodpost, method: :delete,
                                    data: { confirm: "You sure?" },
                                    title: foodpost.content %>
  <% end %>
</li>

app/views/foodposts/index.html.erb
<div class="row">
  <div class= "span6">
    <% if signed_in? %>
      <%= image_tag("pizza.png", :id => "pizza") %>
      <%= render 'shared/foodpost_form' %>
    <% else %>
      <%= image_tag("pizza.png", :id => "pizza-no-hover") %>
    <% end %>
    <ol class="foodposts">
      <%= render @foodposts %>
    </ol>
    <%= will_paginate %>
  </div>
  <div class="span6">
    <span id="map-canvas" style="height: 500px; width: 500px;"></span>
    <span id="main-map" style="height: 1px;"></span>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://rcos.rpi.edu/projects/yumyum1/">RCOS</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://github.com/tboneyang/YumYum">github</a>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <p id="logo">
      <%= link_to "YumYum", root_path, id: "logo" %>
    </p>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",    root_path,
                    'data-no-turbolink' => true %></li>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Campus",  campus_path,
                    'data-no-turbolink' => true %></li>
            <% if signed_in? %>
              <li class="dropdown">
                <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YumYum!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyA8ADmLsnKDH5L0wBCmavBbdW9-Q_ZkfvA' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="foodposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li class="foodpost">
  <span class="date"><%= feed_item.date.strftime("%a %m/%e") %>
  @
  <span class="time"><%= feed_item.start_time.localtime.strftime("%l:%M %p") %></span>
  <span class="location"><%= feed_item.location %></span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                    data: { confirm: "You sure?" },
                                    title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_foodpost_form.html.erb
<%= form_for(@foodpost, ) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" id="new-post">
    <p id="formheader">Add New Event</p>
    <%= f.text_area :content, placeholder: "Describe Your Event...",
                    :class => 'content', :required => 'required' %>
    <div class="counter" style="text-align: right;"></div>
    <p id="formheader">When</p>
    <%= f.text_field :date, :class => 'datepicker' , :required => 'required'%>
    <%= f.time_field :start_time, :ampm => true, :minute_step => 30,
                                 :required => 'required' %>
    </br><p id="formheader">Where</p>
    <%= f.text_field :location, placeholder: " ex: Rickets 201", 
                     :class => 'location', :required => 'required'%>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.foodposts.count, "foodpost") %>
</span>

app/views/static_pages/about.html.erb
<div id="center hero-unit">
  <h1>What is YumYum?</h1>
  <h2 class="about">
  YumYum is a web application designed to help RPI students find free food across campus!
  </h2>
</div>

app/views/static_pages/campus.html.erb
<div class="row">
  <div class="span12">
    <div id="main-map" style="height:500px;"></div>
    <div id="map-canvas" style="height:1px;"></div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div>
  <h1>Co-Founders</h1>
  <h2>
  <span id="tom">Thomas Lixing Yang & </span>
  <span id="arya">Arya Seghatoleslami</span>
  </h2>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="span6">
    <% if signed_in? %>
      <%= image_tag("pizza.png", :id => "pizza") %>
      <%= render 'shared/foodpost_form' %>
    <% else %>
      <%= image_tag("pizza.png", :id => "pizza-no-hover") %>
    <% end %>
    <ol class="foodposts">
      <%= render 'shared/feed' %>
    </ol>
  </div>
  <div class="span6">
    <span id="map-canvas" style="height: 400px; width: 400px;"></span>
    <span id="main-map" style="height: 1px;"></span>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

    <% end %>

    <%= gravatar_for(@user) %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, :required => "required" %>

      <%= f.label :email %>
      <%= f.text_field :email, :required => "required" %>

      <%= f.label :password %>
      <%= f.password_field :password, :required => "required" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :required => "required" %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.foodposts.any? %>
      <h3>Foodposts (<%= @user.foodposts.count %>)</h3>
      <ol class="foodposts">
        <%= render @foodposts %>
      </ol>
      <%= will_paginate @foodposts %>
    <% end %>
  </div>
</div>